### ISSUE TITLE
Core cell difference between ESRI and JTS bindings

### ISSUE THREAD

**Issue by edurdevic** [databrickslabs/mosaic#101] opened 2022-04-19 09:13 UTC
**Describe the bug**
The mosaic_explode of dataframe 
```
        val rdd = spark.sparkContext.makeRDD(Seq(
            Row("POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))")
        ))
        val schema = StructType(
            List(
                StructField("wkt", StringType)
            )
        )
        val df = spark.createDataFrame(rdd, schema)
```
gives two different sets of core geometries when using ESRI vs JTS bindings

**To Reproduce**
Execute with the two different bindings
```
val emptyChips = df
    .select(
        mosaic_explode(col("wkt"), 4, false)
    )
    .filter(col("index.wkb").isNull)
```

One will return 3 core chips and the other will return 4 core chips

**Expected behavior**
Both should return the same core chips

**Comment by rsdavis** [comment] 2022-07-26 15:43
I can confirm the reported differences.

I investigated the issue a bit further, and it appears that the problem is on the H3 side. A core cell is being mistaken for a border cell (esri gets it correct).

The problem is that when populating the core chips, mosaic uses a "carved" geometry that does not overlap the centroid of the core chip. The input geometry gets carved just beyond the centroid so that the polyfill does not include the chip in the core set. 

The `radius` used to carve the geometry is calculated using a maximum "diameter". So, it makes sense that this would happen. If the hexagon is sitting flush with the edge of the boundary, then carving the geometry by the length of the longest leg will overshoot the centroid. So, why didn't this happen with the ESRI bindings? The Esri index system produces the exact same radius, so I think it is simply that buffering is not an exact science.

However, I'm not sure how big of an issue this is. Mistaking a core chip for a border chip likely does not cause accuracy issues in terms of performing a spatial join.

![Screen Shot 2022-07-25 at 6 07 50 PM](https://user-images.githubusercontent.com/5125437/181049724-ede02f08-dc7d-4d3a-aa3d-4785899e3ed8.png)

**Comment by edurdevic** [comment] 2022-07-29 10:13
Interesting! Thanks for looking into this @rsdavis!

This should not be a problem for the spatial join. The main down-side I am aware of is that there will be an extra `st_intersection` performed on the chip if that is marked as `non-core` (which can be skipped for core geometries).

Ps. Are you still using a pre-alpha release? The h3 property of the chips has been renamed to `index_id` in March.

**Comment by r3stl355** [comment] 2023-04-20 21:52
I have a fix for this it's of interest. It looks like Mosaic checks for core chips in 2 places - in a dedicated logic focused on core chips only, and also when it's checking the border chips. The difference explained in this issue is happening in the second (border) check and is caused by a few things: rounding and normalization in JTS in few places, both can be tweaked to match the ESRI behaviour

**Comment by milos-colic** [comment] 2024-01-02 10:43
ESRI will be deprecated in v0.4.x
I will close this issue since we wont be fixing retroactively any ESRI based issues.

**Closed by milos-colic** 2024-01-02 10:43 UTC
