### ISSUE TITLE
AnalysisException when attempting to apply Databricks Mosaic geospatial indexing function

### ISSUE THREAD

**Issue by keval-ll** [databrickslabs/mosaic#380] opened 2023-05-15 21:50 UTC
I have a spark DataFrame with h3 hex ids and I am trying to obtain the polygon geometries. I run into exceptions when attempting to apply spatial indexing functions. 

```
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr
from pyspark.databricks.sql.functions import *

from mosaic import enable_mosaic
enable_mosaic(spark, dbutils)


# Create a Spark session
spark = SparkSession.builder.appName("Mosaic").getOrCreate()

# Create a DataFrame with hex IDs
df = spark.createDataFrame([
    (1, "87422c2a9ffffff"),
    (2, "87422c2a9000000"),
    (3, "87422c2a8ffffff")
], ("id", "h3hex_id"))


df2 = df.withColumn("geometry", grid_boundary(col("h3hex_id"), format_name="WKT"))
df2.sample(fraction=0.1).show()


AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `WKT` cannot be resolved. Did you mean one of the following? ..


```

How do I resolve the exception? I do not have an explicit `WKT` label column in the DataFrame.

**Comment by milos-colic** [comment] 2023-05-16 15:02
@keval-ll 

I believe the issue is happening due to spark planner interpretering "WKT" as a column name in pyspark.
Could you wrap it into F.lit("WKT")?
This should fix the issue.

![Screenshot 2023-05-16 at 16 02 26](https://github.com/databrickslabs/mosaic/assets/75583254/c1c6f92c-7a50-4dca-9f67-999d7ca9cd5c)

**Comment by milos-colic** [comment] 2023-05-31 20:42
@keval-ll  I will close this ticket since I have provided a code that works. In case you have any other issues please open a new ticket.

**Closed by milos-colic** 2023-05-31 20:42 UTC
